import type { JRDBFormatDefinition } from '../parsers/formatParser'
import { JRDBFieldType } from '../parsers/fieldParser'

/**
 * SEC（JRDB成績速報データ（SEC））のフォーマット定義
 * 
 * 
 * レコード長: 346バイト
 */
export const secFormat: JRDBFormatDefinition = {
  dataType: 'SEC',
  description: 'JRDB成績速報データ（SEC）',
  recordLength: 346,
  encoding: 'ShiftJIS',
  lineEnding: 'CRLF',
  fields: [
    { name: '場コード', start: 1, length: 2, type: JRDBFieldType.INTEGER_NINE, description: '場コード' },
    { name: '年', start: 3, length: 2, type: JRDBFieldType.INTEGER_NINE, description: '年' },
    { name: '回', start: 5, length: 1, type: JRDBFieldType.INTEGER_NINE, description: '回' },
    { name: '日', start: 6, length: 1, type: JRDBFieldType.STRING_HEX, description: '16進数(数字 or 小文字アルファベット)' },
    { name: 'R', start: 7, length: 2, type: JRDBFieldType.INTEGER_NINE, description: 'Ｒ' },
    { name: '馬番', start: 9, length: 2, type: JRDBFieldType.INTEGER_NINE, description: '馬番' },
    { name: '血統登録番号', start: 11, length: 8, type: JRDBFieldType.STRING, description: '血統登録番号' },
    { name: '年月日', start: 19, length: 8, type: JRDBFieldType.INTEGER_NINE, description: 'YYYYMMDD <-暫定版より順序' },
    { name: '馬名', start: 27, length: 36, type: JRDBFieldType.STRING, description: '全角１８文字 <-入れ替え' },
    { name: '距離', start: 63, length: 4, type: JRDBFieldType.INTEGER_NINE, description: '距離' },
    { name: '芝ダ障害コード', start: 67, length: 1, type: JRDBFieldType.INTEGER_NINE, description: '1:芝, 2:ダート, 3:障害' },
    { name: '右左', start: 68, length: 1, type: JRDBFieldType.INTEGER_NINE, description: '1:右, 2:左, 3:直, 9:他' },
    { name: '内外', start: 69, length: 1, type: JRDBFieldType.INTEGER_NINE, description: '1:通常(内), 2:外, 3,直ダ, 9:他' },
    { name: '馬場状態', start: 70, length: 2, type: JRDBFieldType.INTEGER_NINE, description: '馬場状態' },
    { name: '種別', start: 72, length: 2, type: JRDBFieldType.INTEGER_NINE, description: '４歳以上等、→成績データの説明' },
    { name: '条件', start: 74, length: 2, type: JRDBFieldType.STRING, description: '900万下等、 →成績データの説明' },
    { name: '記号', start: 76, length: 3, type: JRDBFieldType.INTEGER_NINE, description: '○混等、 →成績データの説明' },
    { name: '重量', start: 79, length: 1, type: JRDBFieldType.INTEGER_NINE, description: 'ハンデ等、 →成績データの説明' },
    { name: 'グレード', start: 80, length: 1, type: JRDBFieldType.INTEGER_NINE, description: 'グレード' },
    { name: 'レース名', start: 81, length: 50, type: JRDBFieldType.STRING, description: 'レース名の通称（全角２５文字）' },
    { name: '頭数', start: 131, length: 2, type: JRDBFieldType.INTEGER_NINE, description: '頭数' },
    { name: 'レース名略称', start: 133, length: 8, type: JRDBFieldType.STRING, description: '全角４文字' },
    { name: '着順', start: 141, length: 2, type: JRDBFieldType.INTEGER_NINE, description: '着順' },
    { name: '異常区分', start: 143, length: 1, type: JRDBFieldType.INTEGER_NINE, description: '異常区分' },
    { name: 'タイム', start: 144, length: 4, type: JRDBFieldType.INTEGER_NINE, description: '0.1秒単位' },
    { name: '斤量', start: 148, length: 3, type: JRDBFieldType.INTEGER_NINE, description: '0.1Kg単位' },
    { name: '騎手名', start: 151, length: 12, type: JRDBFieldType.STRING, description: '全角６文字' },
    { name: '調教師名', start: 163, length: 12, type: JRDBFieldType.STRING, description: '全角６文字' },
    { name: '確定単勝オッズ', start: 175, length: 6, type: JRDBFieldType.STRING, description: '確定単勝オッズ' },
    { name: '確定単勝人気順位', start: 181, length: 2, type: JRDBFieldType.INTEGER_NINE, description: '確定単勝人気順位' },
    { name: 'ＩＤＭ', start: 183, length: 3, type: JRDBFieldType.INTEGER_ZERO_BLANK, description: 'ＩＤＭ' },
    { name: '素点', start: 186, length: 3, type: JRDBFieldType.INTEGER_ZERO_BLANK, description: '素点' },
    { name: '馬場差', start: 189, length: 3, type: JRDBFieldType.INTEGER_ZERO_BLANK, description: '馬場差' },
    { name: 'ペース', start: 192, length: 3, type: JRDBFieldType.STRING, description: 'ペース' },
    { name: '出遅', start: 195, length: 3, type: JRDBFieldType.STRING, description: '出遅' },
    { name: '位置取', start: 198, length: 3, type: JRDBFieldType.STRING, description: '位置取' },
    { name: '不利', start: 201, length: 3, type: JRDBFieldType.STRING, description: '不利' },
    { name: '前不利', start: 204, length: 3, type: JRDBFieldType.STRING, description: '前３Ｆ内での不利' },
    { name: '中不利', start: 207, length: 3, type: JRDBFieldType.STRING, description: '道中での不利' },
    { name: '後不利', start: 210, length: 3, type: JRDBFieldType.STRING, description: '後３Ｆ内での不利' },
    { name: 'レース', start: 213, length: 3, type: JRDBFieldType.STRING, description: 'レース' },
    { name: 'コース取り', start: 216, length: 1, type: JRDBFieldType.INTEGER_NINE, description: 'コース取り' },
    { name: '上昇度コード', start: 217, length: 1, type: JRDBFieldType.INTEGER_NINE, description: '1:AA, 2:A, 3:B, 4:C, 5:D' },
    { name: 'クラスコード', start: 218, length: 2, type: JRDBFieldType.INTEGER_NINE, description: 'クラスコード' },
    { name: '馬体コード', start: 220, length: 1, type: JRDBFieldType.INTEGER_NINE, description: '馬体コード' },
    { name: '気配コード', start: 221, length: 1, type: JRDBFieldType.INTEGER_NINE, description: '気配コード' },
    { name: 'レースペース', start: 222, length: 1, type: JRDBFieldType.STRING, description: 'H:ハイ, M:平均, S:スロー' },
    { name: '馬ペース', start: 223, length: 1, type: JRDBFieldType.STRING, description: '馬自身のペース(H:M:S)' },
    { name: 'テン指数', start: 224, length: 5, type: JRDBFieldType.STRING, description: '前３Ｆタイムを指数化したもの' },
    { name: '上がり指数', start: 229, length: 5, type: JRDBFieldType.STRING, description: '後３Ｆタイムを指数化したもの' },
    { name: 'ペース指数', start: 234, length: 5, type: JRDBFieldType.STRING, description: '馬のペースを指数化したもの' },
    { name: 'レースＰ指数', start: 239, length: 5, type: JRDBFieldType.STRING, description: 'レースのペースを指数化したもの' },
    { name: '1(2)着馬名', start: 244, length: 12, type: JRDBFieldType.STRING, description: '全角６文字' },
    // 1(2)着タイム差（3個、3バイト×3=9バイト）
    ...Array.from({ length: 3 }, (_, i) => ({
      name: `1(2)着タイム差${i + 1}`,
      start: 256 + i * 3,
      length: 3,
      type: JRDBFieldType.INTEGER_NINE as const,
      description: `0.1秒単位${i + 1}`
    })),
    { name: '備考', start: 265, length: 24, type: JRDBFieldType.STRING, description: '全角１２文字（地方競馬場名等）' },
    { name: '予備', start: 289, length: 2, type: JRDBFieldType.STRING, description: 'スペース' },
    // 確定複勝オッズ下（3個、6バイト×3=18バイト）
    ...Array.from({ length: 3 }, (_, i) => ({
      name: `確定複勝オッズ下${i + 1}`,
      start: 291 + i * 6,
      length: 6,
      type: JRDBFieldType.STRING as const,
      description: `最終的な複勝オッズ（下限）${i + 1}`
    })),
    { name: 'コーナー順位1', start: 309, length: 2, type: JRDBFieldType.INTEGER_NINE, description: 'コーナー順位１' },
    { name: 'コーナー順位2', start: 311, length: 2, type: JRDBFieldType.INTEGER_NINE, description: 'コーナー順位２' },
    { name: 'コーナー順位3', start: 313, length: 2, type: JRDBFieldType.INTEGER_NINE, description: 'コーナー順位３' },
    { name: 'コーナー順位4', start: 315, length: 2, type: JRDBFieldType.INTEGER_NINE, description: 'コーナー順位４' },
    { name: '前3Ｆ先頭差', start: 317, length: 3, type: JRDBFieldType.INTEGER_NINE, description: '前３Ｆ地点での先頭とのタイム差' },
    { name: '後3Ｆ先頭差', start: 320, length: 3, type: JRDBFieldType.INTEGER_NINE, description: '後３Ｆ地点での先頭とのタイム差' },
    { name: '騎手コード', start: 323, length: 5, type: JRDBFieldType.INTEGER_NINE, description: '騎手マスタとリンク' },
    { name: '調教師コード', start: 328, length: 5, type: JRDBFieldType.INTEGER_NINE, description: '調教師マスタとリンク' },
    { name: '馬体重', start: 333, length: 3, type: JRDBFieldType.INTEGER_NINE, description: 'データ無:スペース' },
    { name: '馬体重増減', start: 336, length: 3, type: JRDBFieldType.STRING, description: '符号+数字２桁、データ無:スペース' },
    { name: '天候コード', start: 339, length: 1, type: JRDBFieldType.INTEGER_NINE, description: 'コード表参照' },
    { name: 'コース', start: 340, length: 1, type: JRDBFieldType.STRING, description: '1:A,2:A1,3:A2,4:B,5:C,6:D' },
    { name: 'レース脚質', start: 341, length: 1, type: JRDBFieldType.STRING, description: '脚質コード参照' },
    { name: '予備', start: 342, length: 3, type: JRDBFieldType.STRING, description: 'スペース' },
    { name: '改行', start: 345, length: 2, type: JRDBFieldType.STRING, description: 'ＣＲ・ＬＦ' },
  ]
}
