name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Volta and install node
      uses: volta-cli/action@v1
          
    - name: Install node and pnpm
      run: volta install node pnpm
      
    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: $(pnpm store path --silent)
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
          
    - name: Install dependencies
      run: pnpm install
      
    - name: Run lint
      run: pnpm turbo lint
      
    - name: Run lint:fix check
      run: |
        # 修正可能なlintエラーがないことを確認
        pnpm turbo lint:fix
        # 修正後に再度lintを実行して、まだエラーが残っていないかチェック
        pnpm turbo lint
